### ISSUE TITLE
Game description under readme section

### ISSUE THREAD

**Issue by Niyatizzz** [ChromeGaming/PACKABUNCHAS#23]
### Describe the bug ✍️

Hii adding the game description can enhance the readme section and also allow users to get an idea on how the game works

### Provide step by step information reproduce the bug 📄

I would like to add step by step procedure on enjoying the game and wish to to contribute to this project under gssoc'24

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Priti9075** [comment]
I'm incredibly enthusiastic about tackling the "Game description under readme section." issue for GSoC 2024! My skills in HTML , CSS , JS perfectly align with this project's needs. Is there a possibility of me being assigned this issue?

**Comment by somiljainspace** [comment]
Describe the bug ✍️

Hii adding the game description can enhance the readme section and also allow users to get an idea on how the game works

Provide step by step information reproduce the bug 📄

I wish to to contribute to this project under gssoc'24

Select program in which you are contributing

GSSoC24

Code of Conduct

 I follow [CONTRIBUTING GUIDELINE](https://github.com/ChromeGaming/PACKABUNCHAS/issues/23) of this project.
