### ISSUE TITLE
[New Feature]: Favicon change

### ISSUE THREAD

**Issue by ananya-sh30** [ChromeGaming/PACKABUNCHAS#69]
### 🎮 feature Request

Hi I would like to change the favicon icon of the website and replace it with the actual logo of the website instead of an emoji to make it look more appealing and professional. 
Here is the reference of the issue I am referring to:
![Screenshot 2024-06-03 131744](https://github.com/ChromeGaming/PACKABUNCHAS/assets/142817946/14a879e5-1792-4a97-941b-5e594f124cc9)

### Point down the features

This logo can be used as the favicon
![Screenshot 2024-06-03 132057](https://github.com/ChromeGaming/PACKABUNCHAS/assets/142817946/c56739de-3511-4254-b890-d934643119ff)

Please consider assigning this issue to me along with gssoc labels

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by jayanththalla** [comment]
please assign me @pa
