### ISSUE TITLE
Add a dark/bright mode toggle button

### ISSUE THREAD

**Issue by ananyag309** [ChromeGaming/PACKABUNCHAS#72]
### 🎮 feature Request

feature logic and basic description - By integrating a dark/bright mode toggle button and implementing the feature logic users can enjoy a more personalized and comfortable viewing experience while using the website or app.

### Point down the features

feature points - It will enhance the user playing game in their comfort mode

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Vikashchou-dhary** [comment]
i would like to this issue plz assign it me

**Comment by ananyag309** [comment]
Please assign this issue to me. I have recently fixed the same issue in other website too.

![tog](https://github.com/ChromeGaming/PACKABUNCHAS/assets/145869907/0981579c-6eb7-4af8-8a59-8e61e9812069)
![togg](https://github.com/ChromeGaming/PACKABUNCHAS/assets/145869907/45ac04e9-2c00-4356-a350-6f5d9a1cc613)
