### ISSUE TITLE
[Documentation Bug]: uses techstack in the project

### ISSUE THREAD

**Issue by Debayan-Ghosh2005** [ChromeGaming/PACKABUNCHAS#86]
### Describe the bug ✍️

there is no written which techstack use in the project

### Provide step by step information reproduce the bug 📄

i will read all the code file then i will add it readme file

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Debayan-Ghosh2005** [comment]
i am very new at gssoc24 can you assign it to me

**Comment by JagjeetChauhan** [comment]
Can you assign this task to me
